# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/clion/177/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /snap/clion/177/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hp/Documents/Code/C++/JAVAQUARIUM

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hp/Documents/Code/C++/JAVAQUARIUM/cmake-build-debug

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/clion/177/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/snap/clion/177/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hp/Documents/Code/C++/JAVAQUARIUM/cmake-build-debug/CMakeFiles /home/hp/Documents/Code/C++/JAVAQUARIUM/cmake-build-debug//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hp/Documents/Code/C++/JAVAQUARIUM/cmake-build-debug/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named JAVAQUARIUM

# Build rule for target.
JAVAQUARIUM: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JAVAQUARIUM
.PHONY : JAVAQUARIUM

# fast build rule for target.
JAVAQUARIUM/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JAVAQUARIUM.dir/build.make CMakeFiles/JAVAQUARIUM.dir/build
.PHONY : JAVAQUARIUM/fast

algue.o: algue.cpp.o
.PHONY : algue.o

# target to build an object file
algue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JAVAQUARIUM.dir/build.make CMakeFiles/JAVAQUARIUM.dir/algue.cpp.o
.PHONY : algue.cpp.o

algue.i: algue.cpp.i
.PHONY : algue.i

# target to preprocess a source file
algue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JAVAQUARIUM.dir/build.make CMakeFiles/JAVAQUARIUM.dir/algue.cpp.i
.PHONY : algue.cpp.i

algue.s: algue.cpp.s
.PHONY : algue.s

# target to generate assembly for a file
algue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JAVAQUARIUM.dir/build.make CMakeFiles/JAVAQUARIUM.dir/algue.cpp.s
.PHONY : algue.cpp.s

aquarium.o: aquarium.cpp.o
.PHONY : aquarium.o

# target to build an object file
aquarium.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JAVAQUARIUM.dir/build.make CMakeFiles/JAVAQUARIUM.dir/aquarium.cpp.o
.PHONY : aquarium.cpp.o

aquarium.i: aquarium.cpp.i
.PHONY : aquarium.i

# target to preprocess a source file
aquarium.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JAVAQUARIUM.dir/build.make CMakeFiles/JAVAQUARIUM.dir/aquarium.cpp.i
.PHONY : aquarium.cpp.i

aquarium.s: aquarium.cpp.s
.PHONY : aquarium.s

# target to generate assembly for a file
aquarium.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JAVAQUARIUM.dir/build.make CMakeFiles/JAVAQUARIUM.dir/aquarium.cpp.s
.PHONY : aquarium.cpp.s

general.o: general.cpp.o
.PHONY : general.o

# target to build an object file
general.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JAVAQUARIUM.dir/build.make CMakeFiles/JAVAQUARIUM.dir/general.cpp.o
.PHONY : general.cpp.o

general.i: general.cpp.i
.PHONY : general.i

# target to preprocess a source file
general.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JAVAQUARIUM.dir/build.make CMakeFiles/JAVAQUARIUM.dir/general.cpp.i
.PHONY : general.cpp.i

general.s: general.cpp.s
.PHONY : general.s

# target to generate assembly for a file
general.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JAVAQUARIUM.dir/build.make CMakeFiles/JAVAQUARIUM.dir/general.cpp.s
.PHONY : general.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JAVAQUARIUM.dir/build.make CMakeFiles/JAVAQUARIUM.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JAVAQUARIUM.dir/build.make CMakeFiles/JAVAQUARIUM.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JAVAQUARIUM.dir/build.make CMakeFiles/JAVAQUARIUM.dir/main.cpp.s
.PHONY : main.cpp.s

objetaquarium.o: objetaquarium.cpp.o
.PHONY : objetaquarium.o

# target to build an object file
objetaquarium.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JAVAQUARIUM.dir/build.make CMakeFiles/JAVAQUARIUM.dir/objetaquarium.cpp.o
.PHONY : objetaquarium.cpp.o

objetaquarium.i: objetaquarium.cpp.i
.PHONY : objetaquarium.i

# target to preprocess a source file
objetaquarium.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JAVAQUARIUM.dir/build.make CMakeFiles/JAVAQUARIUM.dir/objetaquarium.cpp.i
.PHONY : objetaquarium.cpp.i

objetaquarium.s: objetaquarium.cpp.s
.PHONY : objetaquarium.s

# target to generate assembly for a file
objetaquarium.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JAVAQUARIUM.dir/build.make CMakeFiles/JAVAQUARIUM.dir/objetaquarium.cpp.s
.PHONY : objetaquarium.cpp.s

poisson.o: poisson.cpp.o
.PHONY : poisson.o

# target to build an object file
poisson.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JAVAQUARIUM.dir/build.make CMakeFiles/JAVAQUARIUM.dir/poisson.cpp.o
.PHONY : poisson.cpp.o

poisson.i: poisson.cpp.i
.PHONY : poisson.i

# target to preprocess a source file
poisson.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JAVAQUARIUM.dir/build.make CMakeFiles/JAVAQUARIUM.dir/poisson.cpp.i
.PHONY : poisson.cpp.i

poisson.s: poisson.cpp.s
.PHONY : poisson.s

# target to generate assembly for a file
poisson.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JAVAQUARIUM.dir/build.make CMakeFiles/JAVAQUARIUM.dir/poisson.cpp.s
.PHONY : poisson.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... JAVAQUARIUM"
	@echo "... algue.o"
	@echo "... algue.i"
	@echo "... algue.s"
	@echo "... aquarium.o"
	@echo "... aquarium.i"
	@echo "... aquarium.s"
	@echo "... general.o"
	@echo "... general.i"
	@echo "... general.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... objetaquarium.o"
	@echo "... objetaquarium.i"
	@echo "... objetaquarium.s"
	@echo "... poisson.o"
	@echo "... poisson.i"
	@echo "... poisson.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

